$(() => {
	console.log('JS works');

	// Buttons
	const $populateForm = $('#populateForm');
	const $editForm = $('#editForm');
	// Form input constants
	const $input = $('.input');
	const $input_first_name = $('#input_first_name'); 
	const $input_last_name = $('#input_last_name'); 
	const $input_img_link = $('#input_img_link');
	const $input_rank = $('#input_rank'); 
	const $input_age = $('#input_age'); 
	const $input_height = $('#input_height'); 
	const $input_dob = $('#input_dob'); 
	const $input_dob_month = $('#input_dob_month'); 
	const $input_next_of_kin_1 = $('#input_next_of_kin_1'); 
	const $input_next_of_kin_2 = $('#input_next_of_kin_2'); 
	const $input_residence = $('#input_residence'); 
	const $input_place_of_birth = $('#input_place_of_birth'); 
	const $input_primary_specialisations_1 = $('#input_primary_specialisations_1'); 
	const $input_primary_specialisations_2 = $('#input_primary_specialisations_2'); 
	const $input_primary_specialisations_3 = $('#input_primary_specialisations_3'); 
	const $input_additional_skills_1 = $('#input_additional_skills_1'); 
	const $input_additional_skills_2 = $('#input_additional_skills_2'); 
	const $input_additional_skills_3 = $('#input_additional_skills_3'); 
	const $input_languages_1 = $('#input_languages_1'); 
	const $input_languages_2 = $('#input_languages_2'); 
	const $input_languages_3 = $('#input_languages_3'); 
	const $input_languages_4 = $('#input_languages_4'); 
	const $input_mentors_1 = $('#input_mentors_1'); 
	const $input_mentors_2 = $('#input_mentors_2'); 
	const $input_mentors_3 = $('#input_mentors_3'); 
	const $input_additional_info_1 = $('#input_additional_info_1'); 
	const $input_additional_info_2 = $('#input_additional_info_2'); 
	const $input_additional_info_3 = $('#input_additional_info_3'); 
	const $input_organisation_1 = $('#input_organisation_1'); 
	const $input_position_11 = $('#input_position_11');
	const $input_position_12 = $('#input_position_12'); 
	const $input_position_13 = $('#input_position_13'); 
	const $input_organisation_2 = $('#input_organisation_2'); 
	const $input_position_21 = $('#input_position_21');
	const $input_position_22 = $('#input_position_22'); 
	const $input_position_23 = $('#input_position_23');
	const $input_organisation_3 = $('#input_organisation_3'); 
	const $input_position_31 = $('#input_position_31');
	const $input_position_32 = $('#input_position_32'); 
	const $input_position_33 = $('#input_position_33');
	const $input_organisation_4 = $('#input_organisation_4'); 
	const $input_position_41 = $('#input_position_41');
	const $input_position_42 = $('#input_position_42'); 
	const $input_position_43 = $('#input_position_43');
	const $input_organisation_5 = $('#input_organisation_5'); 
	const $input_position_51 = $('#input_position_51');
	const $input_position_52 = $('#input_position_52'); 
	const $input_position_53 = $('#input_position_53');
	const $input_discredit_1 = $('#input_discredit_1');
	const $input_discredit_2 = $('#input_discredit_2'); 
	const $input_discredit_3 = $('#input_discredit_3');  

// result constants
	const $results = $('.results');	
	const $ref_img_link = $('#ref_img_link');
	const $img_link = $('#img_link');
	const $first_name = $('#first_name');
	const $last_name = $('#last_name');
	const $rank = $('#rank');
	const $age = $('#age');
	const $height = $('#height');
	const $dob = $('#dob');
	const $dob_month = $('#dob_month');
	const $next_of_kin_1 = $('#next_of_kin_1');
	const $next_of_kin_2 = $('#next_of_kin_2');
	const $residence = $('#residence');
	const $place_of_birth = $('#place_of_birth');
	const $primary_specialisations_1 = $('#primary_specialisations_1');
	const $primary_specialisations_2 = $('#primary_specialisations_2');
	const $primary_specialisations_3 = $('#primary_specialisations_3');
	const $additional_skills_1 = $('#additional_skills_1');
	const $additional_skills_2 = $('#additional_skills_2');
	const $additional_skills_3 = $('#additional_skills_3');
	const $languages_1 = $('#languages_1');
	const $languages_2 = $('#languages_2');
	const $languages_3 = $('#languages_3');
	const $languages_4 = $('#languages_4');
	const $mentors_1 = $('#mentors_1');
	const $mentors_2 = $('#mentors_2');
	const $mentors_3 = $('#mentors_3');
	const $additional_info_1 = $('#additional_info_1');
	const $additional_info_2 = $('#additional_info_2');
	const $additional_info_3 = $('#additional_info_3');
	const $organisation_1 = $('#organisation_1'); 
	const $position_11 = $('#position_11');
	const $position_12 = $('#position_12'); 
	const $position_13 = $('#position_13'); 
	const $organisation_2 = $('#organisation_2'); 
	const $position_21 = $('#position_21');
	const $position_22 = $('#position_22'); 
	const $position_23 = $('#position_23');
	const $organisation_3 = $('#organisation_3'); 
	const $position_31 = $('#position_31');
	const $position_32 = $('#position_32'); 
	const $position_33 = $('#position_33');
	const $organisation_4 = $('#organisation_4'); 
	const $position_41 = $('#position_41');
	const $position_42 = $('#position_42'); 
	const $position_43 = $('#position_43');
	const $organisation_5 = $('#organisation_5'); 
	const $position_51 = $('#position_51');
	const $position_52 = $('#position_52'); 
	const $position_53 = $('#position_53');
	const $discredit_1 = $('#discredit_1');
	const $discredit_2 = $('#discredit_2'); 
	const $discredit_3 = $('#discredit_3');

	$editForm.on('click', ()=> {
		$input.show();
		$results.hide();
	});

	$results.hide();
	$populateForm.on('click', ()=> {
		$input.hide();
		$results.show();
		$img_link.attr('src', $input_img_link.val());
		$first_name.text($input_first_name.val());
		$last_name.text($input_last_name.val());
		$rank.text($input_rank.val())
		$age.text($input_age.val());
		$height.text($input_height.val());
		$dob.text($input_dob.val());
		$dob_month.text($input_dob_month.val());
		$next_of_kin_1.text($input_next_of_kin_1.val());
		$next_of_kin_2.text($input_next_of_kin_2.val());
		$residence.text($input_residence.val());
		$place_of_birth.text($input_place_of_birth.val());
		$primary_specialisations_1.text($input_primary_specialisations_1.val());
		$primary_specialisations_2.text($input_primary_specialisations_2.val());
		$primary_specialisations_3.text($input_primary_specialisations_3.val());
		$additional_skills_1.text($input_additional_skills_1.val());
		$additional_skills_2.text($input_additional_skills_2.val());
		$additional_skills_3.text($input_additional_skills_3.val());
		$languages_1.text($input_languages_1.val());
		$languages_2.text($input_languages_2.val());
		$languages_3.text($input_languages_3.val());
		$languages_4.text($input_languages_4.val());
		$mentors_1.text($input_mentors_1.val());
		$mentors_2.text($input_mentors_2.val());
		$mentors_3.text($input_mentors_3.val());
		$additional_info_1.text($input_additional_info_1.val());
		$additional_info_2.text($input_additional_info_2.val());
		$additional_info_3.text($input_additional_info_3.val());
		$organisation_1.text($input_organisation_1.val());
		$position_11.text($input_position_11.val());
		$position_12.text($input_position_12.val());
		$position_13.text($input_position_13.val());
		$organisation_2.text($input_organisation_2.val());
		$position_21.text($input_position_21.val());
		$position_22.text($input_position_22.val());
		$position_23.text($input_position_23.val());
		$organisation_3.text($input_organisation_3.val());
		$position_31.text($input_position_31.val());
		$position_32.text($input_position_32.val());
		$position_33.text($input_position_33.val());
		$organisation_4.text($input_organisation_4.val());
		$position_41.text($input_position_41.val());
		$position_42.text($input_position_42.val());
		$position_43.text($input_position_43.val());
		$organisation_5.text($input_organisation_5.val());
		$position_51.text($input_position_51.val());
		$position_52.text($input_position_52.val());
		$position_53.text($input_position_53.val());
		$discredit_1.text($input_discredit_1.val());
		$discredit_2.text($input_discredit_2.val());
		$discredit_3.text($input_discredit_3.val());
		
	});
});